spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH-mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mail:
    host: smtp.qq.com
    # 替换成自己的
    username: 
    password: 
    default-encoding: UTF-8
    protocol: smtps
    properties:
      smtp:
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          port: 465
        auth: true
        starttls:
          enable: true
          required: true
    port: 465




lance:
  mail:
    sender: 

server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wust.graproject.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

