spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH-mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mail:
    host: smtp.qq.com
    username: 893052525@qq.com
    password: viypmconisglbbjg
    default-encoding: UTF-8
    protocol: smtp
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

lance:
  mail:
    sender: 893052525@qq.com

server:
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wust.graproject.entity

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

